Repository ETF-TAK/BE, pull requests merged in 2024-12, with the labels that each got.

#37 pr feat/#32-etf-detail-page
  src/main/java/com/example/tak/controller/EtfCompareController.java
  src/main/java/com/example/tak/dto/response/ComponentStockInfo.java
  src/main/java/com/example/tak/dto/response/CurrentPriceData.java
  src/main/java/com/example/tak/dto/response/DistributionInfo.java
  src/main/java/com/example/tak/dto/response/EtfDetailResponse.java
  src/main/java/com/example/tak/dto/response/EtfDetailResult.java
  src/main/java/com/example/tak/dto/response/HistoricalPriceResponse.java
  src/main/java/com/example/tak/dto/response/MarketPriceResponse.java
  src/main/java/com/example/tak/repository/EtfRepository.java
  src/main/java/com/example/tak/service/ComponentStockService.java
  src/main/java/com/example/tak/service/DistributionService.java
  src/main/java/com/example/tak/service/DividendService.java
  src/main/java/com/example/tak/service/EtfComparisonService.java
  src/main/java/com/example/tak/service/EtfDetailService.java
  src/main/java/com/example/tak/service/EtfInfoService.java
  src/main/java/com/example/tak/service/PriceService.java
  src/main/java/com/example/tak/service/StockInfoService.java
  src/main/java/com/example/tak/service/UsDistributionService.java
  src/main/java/com/example/tak/service/UsPriceService.java
Labels: feat ✨, docs 🎨

#39 pr feat/#38-get-etf-invest-list
  src/main/java/com/example/tak/controller/ETFInvestListController.java
  src/main/java/com/example/tak/dto/response/ETFInvestListResponseDTO.java
  src/main/java/com/example/tak/repository/EtfDataRepository.java
  src/main/java/com/example/tak/service/ETFInvestListService.java
Labels: feat ✨

#41 feat: ETF 비교화면 카테고리별 검색 API 구현
  src/main/java/com/example/tak/controller/EtfCompareController.java
  src/main/java/com/example/tak/dto/response/EtfResponseDto.java
  src/main/java/com/example/tak/repository/EtfRepository.java
  src/main/java/com/example/tak/service/EtfCompareListService.java
Labels: feat ✨

#42 feat(#33): 현재가, 등락률 api 연결
  src/main/java/com/example/tak/controller/ETFTagSearchController.java
  src/main/java/com/example/tak/dto/response/ETFTagSearchResponse.java
  src/main/java/com/example/tak/dto/response/ETFTagSearchResponseDTO.java
  src/main/java/com/example/tak/repository/ETFTagSearchRepository.java
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨

#45 pr Feat/#29 etf search
  src/main/java/com/example/tak/controller/ETFInvestController.java
  src/main/java/com/example/tak/dto/request/ETFInvestRequestDto.java
  src/main/java/com/example/tak/dto/response/ETFInvestResponseDto.java
  src/main/java/com/example/tak/repository/EtfDataRepository.java
  src/main/java/com/example/tak/service/ETFInvestService.java
  src/main/java/com/example/tak/service/InvestPriceService.java
  src/main/java/com/example/tak/service/UsInvestService.java
Labels: feat ✨

#48 pr feat#33-feat-etf-sector-search-page
  src/main/java/com/example/tak/controller/ETFTagSearchController.java
  src/main/java/com/example/tak/repository/ETFTagSearchRepository.java
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨

#49 pr feat: ETF 리스트 둘러보기 기능 구현
  src/main/java/com/example/tak/controller/ETFInvestListController.java
  src/main/java/com/example/tak/controller/EtfCompareController.java
  src/main/java/com/example/tak/dto/response/EtfResponseDto.java
  src/main/java/com/example/tak/service/EtfGetListService.java
Labels: feat ✨

#51 feat: 미국 ETF 환율 적용
  src/main/java/com/example/tak/service/InvestPriceService.java
  src/main/java/com/example/tak/service/UsInvestService.java
Labels: feat ✨

#52 [chore] main 병합 2
  src/main/java/com/example/tak/service/InvestPriceService.java
  src/main/java/com/example/tak/service/UsInvestService.java
Labels: chore

#53 pr feat/#33-etf-sector-search-page-api
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨

#54 pr fix/#33-etf-sector-search-page-price
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: fix 🐞

#59 fix(#46): 미국 ETF 환율 재적용
  src/main/java/com/example/tak/service/EtfGetListService.java
  src/main/java/com/example/tak/service/UsPriceService.java
Labels: fix 🐞

#60 pr feat/#33-etf-sector-search-page-us-price
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨

#65 pr feat/#61-sector-navigate
  src/main/java/com/example/tak/dto/response/ETFTagSearchResponseDTO.java
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨

#71 pr feat/#61-front-cors
  src/main/java/com/example/tak/config/CorsMvcConfig.java
Labels: feat ✨

#73 pr fix/#72-fee-type
  src/main/java/com/example/tak/domain/ETF.java
  src/main/java/com/example/tak/dto/response/EtfResponseDto.java
Labels: fix 🐞

#76 pr feat/#61-sector-navigate-cors
  src/main/java/com/example/tak/config/CorsMvcConfig.java
  src/main/resources/application.yml
Labels: feat ✨
