Repository ETF-TAK/BE, pull requests merged in 2024-11, with the labels that each got.

#3 pr settings/#2-settings-swagger
  build.gradle
  src/main/java/com/example/tak/config/SwaggerConfig.java
Labels: settings :hammer_and_wrench:

#4 pr feat/#1-set-up-settings
  .env
  .gitignore
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: settings :hammer_and_wrench:

#6 pr settings/#5-edit-gitignore
  .env
  .gitignore
Labels: settings :hammer_and_wrench:

#14 데이터 불러오기
  src/main/java/com/example/tak/controller/EtfDataController.java
  src/main/java/com/example/tak/domain/ETF.java
  src/main/java/com/example/tak/dto/EtfRequestDto.java
  src/main/java/com/example/tak/repository/EtfDataRepository.java
  src/main/java/com/example/tak/service/EtfDataService.java
  src/main/resources/application.yml
Labels: feat ✨

#16 [feat] 응답 핸들러 작성
  src/main/java/com/example/tak/config/BaseEntity.java
  src/main/java/com/example/tak/config/response/ApiResponse.java
  src/main/java/com/example/tak/config/response/code/BaseCode.java
  src/main/java/com/example/tak/config/response/code/BaseErrorCode.java
  src/main/java/com/example/tak/config/response/code/ErrorReasonDto.java
  src/main/java/com/example/tak/config/response/code/ReasonDto.java
  src/main/java/com/example/tak/config/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/tak/config/response/code/resultCode/SuccessStatus.java
  src/main/java/com/example/tak/config/response/exception/ExceptionAdvice.java
  src/main/java/com/example/tak/config/response/exception/GeneralException.java
  src/main/java/com/example/tak/config/response/exception/handler/EtfHandler.java
  src/main/java/com/example/tak/config/response/exception/handler/GeneralHandler.java
  src/main/java/com/example/tak/domain/Distribution.java
  src/main/java/com/example/tak/domain/ETF.java
  src/main/java/com/example/tak/domain/Stock.java
Labels: feat ✨, settings :hammer_and_wrench:

#18 pr feat/#17-add-converter
  src/main/java/com/example/tak/common/Category.java
  src/main/java/com/example/tak/common/Nation.java
  src/main/java/com/example/tak/converter/CategoryConverter.java
  src/main/java/com/example/tak/converter/NationConverter.java
  src/main/java/com/example/tak/domain/ETF.java
Labels: feat ✨

#22 pr settings/#19-make-dockerfile
  src/main/resources/application.yml
Labels: settings :hammer_and_wrench:

#23 pr merge develop branch into main branch
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/tak/TakApplication.java
  src/main/java/com/example/tak/common/Category.java
  src/main/java/com/example/tak/common/Nation.java
  src/main/java/com/example/tak/config/BaseEntity.java
  src/main/java/com/example/tak/config/SwaggerConfig.java
  src/main/java/com/example/tak/config/response/ApiResponse.java
  src/main/java/com/example/tak/config/response/code/BaseCode.java
  src/main/java/com/example/tak/config/response/code/BaseErrorCode.java
  src/main/java/com/example/tak/config/response/code/ErrorReasonDto.java
  src/main/java/com/example/tak/config/response/code/ReasonDto.java
  src/main/java/com/example/tak/config/response/code/resultCode/ErrorStatus.java
  src/main/java/com/example/tak/config/response/code/resultCode/SuccessStatus.java
  src/main/java/com/example/tak/config/response/exception/ExceptionAdvice.java
  src/main/java/com/example/tak/config/response/exception/GeneralException.java
  src/main/java/com/example/tak/config/response/exception/handler/EtfHandler.java
  src/main/java/com/example/tak/config/response/exception/handler/GeneralHandler.java
  src/main/java/com/example/tak/controller/EtfDataController.java
  src/main/java/com/example/tak/converter/CategoryConverter.java
  src/main/java/com/example/tak/converter/NationConverter.java
  src/main/java/com/example/tak/domain/Distribution.java
  src/main/java/com/example/tak/domain/ETF.java
  src/main/java/com/example/tak/domain/Stock.java
  src/main/java/com/example/tak/dto/EtfRequestDto.java
  src/main/java/com/example/tak/repository/EtfDataRepository.java
  src/main/java/com/example/tak/service/EtfDataService.java
  src/main/resources/application.yml
  src/test/java/com/example/tak/TakApplicationTests.java
Labels: chore

#25 pr settings/#24-env-file-gitignore-addition
  .gitignore
Labels: settings :hammer_and_wrench:

#27 pr feat/#25-feature-deploy-script
  deploy.sh
Labels: feat ✨

#34 33-feat-etf-sector-search-page
  src/main/java/com/example/tak/controller/ETFTagSearchController.java
  src/main/java/com/example/tak/dto/response/ETFTagSearchResponse.java
  src/main/java/com/example/tak/repository/ETFTagSearchRepository.java
  src/main/java/com/example/tak/service/ETFTagSearchService.java
  src/main/resources/application.yml
Labels: feat ✨

#35 33-feat-etf-sector-search-page
  src/main/java/com/example/tak/common/Nation.java
  src/main/java/com/example/tak/config/CorsMvcConfig.java
  src/main/java/com/example/tak/controller/ETFTagSearchController.java
  src/main/java/com/example/tak/controller/TestController.java
  src/main/java/com/example/tak/repository/ETFTagSearchRepository.java
Labels: feat ✨

#36 33-feat-etf-sector-search-page
  src/main/java/com/example/tak/controller/ETFTagSearchController.java
  src/main/java/com/example/tak/repository/ETFTagSearchRepository.java
  src/main/java/com/example/tak/service/ETFTagSearchService.java
Labels: feat ✨
